### ISSUE TITLE
Empty Tiles on Copy

### ISSUE THREAD

**Issue by four43** [mojodna/tl#12]
Hello,

I'm having an issue creating an mbtiles set from a tmsource. There aren't any real helpful errors being thrown which is making this kind of tough to track down.

```
tl copy \
        -r tilelive-tmsource,tilelive-tmstyle,tilelive-mapnik,tilejson,tilelive-vector \
        -z 0 -Z 4 \
        "tmsource:///path/to/my.tm2source" \
        "mbtiles:///path/to/my/tiles/0-8z.mbtiles"

0/0/0   580
1/0/0   580
1/1/0   580
1/0/1   580
1/1/1   580
2/2/0   580
2/0/0   580
2/3/0   580
2/1/0   580
2/0/1   580
...
```

I've tried with and without the "-r" flag, sounds like that is a just in case flag. All the tiles are "580" and there is no indication of error until the very end:

```
4/15/15 580
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:149:15)
    at Readable.push (_stream_readable.js:126:10)
    at null._onTimeout (/usr/local/lib/node_modules/tl/node_modules/tilelive-streaming/index.js:165:12)
    at Timer.listOnTimeout (timers.js:119:15)
```

Any thoughts on what that could be? Anything I can try? The tmsource is a fairly simple project, just a few GeoTiff images that work fine in Mapbox Studio Classic.

Thanks for the help,
-Seth

Edit: So multiple mapbox versions have caused issues in the past, I am just verifying that I only have one version of mapbox installed. Versions:

```
# npm ls -g | grep mapnik
├─┬ mapnik@3.4.6
│ ├── mapnik-vector-tile@0.10.0
├─┬ tilelive-mapnik@0.6.17
│ │ ├── mapnik-reference@7.0.1
│ ├── mapnik-reference@8.4.0
│ │ ├─┬ mapnik-pool@0.1.1
│ │ ├── mapnik-reference@7.0.1

#npm ls -g | grep tile
│ ├── mapnik-vector-tile@0.10.0
│   │ │ ├── cryptiles@2.0.5
├─┬ mbtiles@0.8.0
│ │   │ │ ├── cryptiles@2.0.4
│ └── tiletype@0.1.0
│ ├─┬ tilelive-cache@0.4.5
│ └── tilelive-modules@0.1.4
├─┬ tilejson@1.0.0
│ │   │ ├── cryptiles@2.0.5
│ └── tiletype@0.1.0
├─┬ tilelive@5.9.0
├─┬ tilelive-file@0.0.3
├─┬ tilelive-http@0.8.0
│ │ │ ├── cryptiles@2.0.5
├── tilelive-mapbox@0.4.0
├─┬ tilelive-mapnik@0.6.17
├─┬ tilelive-s3@3.0.0
│ │ │ │ ├── cryptiles@2.0.5
│ └── tiletype@0.1.0
├─┬ tilelive-tmsource@0.4.0
│ ├─┬ tilelive-bridge@1.6.0
├─┬ tilelive-tmstyle@0.4.1
├── tilelive-utfgrid@0.2.0
├─┬ tilelive-vector@3.5.0
│ │ │ ├── cryptiles@0.2.2
  ├─┬ tilelive-cache@0.4.5
  ├── tilelive-modules@0.1.4
  └─┬ tilelive-streaming@0.4.0
    └── tiletype@0.1.0
```

**Comment by four43** [comment]
Thinking this may be linked to my issues with Tessera: https://github.com/mojodna/tessera/issues/29

**Comment by sethfitz** [comment]
Sounds right.  Seems like it's rendering a transparent image because there are no features to render.
