### ISSUE TITLE
Can't run tl

### ISSUE THREAD

**Issue by drax314** [mojodna/tl#24]
Hello, 

I run MacOS Sierra, Node v0.10, and I'm unable to starl `tl` - see log. 
Can you please help me?

thanks a lot! 

```
$ nvm install v0.10
...
$ nvm use v0.10
Now using node v0.10.48 (npm v2.15.1)

$ npm install tl -g
npm WARN engine @mapbox/tilelive@5.12.6: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN deprecated queue-async@1.0.7: renamed to d3-queue
/Users/drax/.nvm/v0.10.48/bin/tl -> /Users/drax/.nvm/v0.10.48/lib/node_modules/tl/bin/tl.js
tl@0.10.1 /Users/drax/.nvm/v0.10.48/lib/node_modules/tl
├── tilelive-modules@0.3.4
├── async@1.5.2
├── nomnom@1.7.0 (underscore@1.4.4, chalk@0.4.0)
├── tilelive-cache@0.7.1 (clone@1.0.2, locking-cache@0.3.0)
├── tilelive-streaming@0.7.7 (@mapbox/sphericalmercator@1.0.5, debug@2.6.8, @mapbox/tiletype@0.3.1, highland@2.11.1)
└── @mapbox/tilelive@5.12.6 (queue-async@1.0.7, minimist@0.2.0, @mapbox/sphericalmercator@1.0.5, progress-stream@0.5.0)

$ tl

util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                          ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.exports.inherits (util.js:556:27)
    at Object.<anonymous> (/Users/drax/.nvm/v0.10.48/lib/node_modules/tl/node_modules/tilelive-streaming/lib/scheme.js:34:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/drax/.nvm/v0.10.48/lib/node_modules/tl/node_modules/tilelive-streaming/index.js:12:14)
 $
```

**Comment by sethfitz** [comment]
One of `tl`'s dependencies (`tilelive-streaming`, initially) is no longer compatible with Node v0.10.x.

I'd recommend using a more recent version of Node (say, 6.x, since it's the current LTS release) and going from there.
