### ISSUE TITLE
Module brakes with Error: Invalid tilesource protocol: mbtiles:

### ISSUE THREAD

**Issue by hyances** [mojodna/tl#28]
Hi!  This is probably a silly question; I've installed mbtiles as follow `npm install -r @mapbox/mbtiles`

Then run the following:

`tl copy -z 13 -Z 20 -b '-75.766611 10.162420 -75.708632 10.189327' 'http://a.tile.openstreetmap.org/{z}/{x}/{y}.png' mbtiles://./orika-osm.mbtiles`

And get this error:
```
/usr/lib/node_modules/tl/lib/commands/copy.js:76
          throw err;
          ^

Error: Invalid tilesource protocol: mbtiles:
    at Object.tilelive.load (/usr/lib/node_modules/tl/node_modules/@mapbox/tilelive/lib/tilelive.js:94:25)
    at Object.tilelive.load (/usr/lib/node_modules/tl/node_modules/tilelive-streaming/index.js:533:12)
    at Object.tilelive.load (/usr/lib/node_modules/tl/node_modules/tilelive-streaming/index.js:533:12)
    at /usr/lib/node_modules/tl/node_modules/tilelive-cache/index.js:266:23
    at lock (/usr/lib/node_modules/tl/node_modules/locking-cache/index.js:57:16)
    at Object.<anonymous> (/usr/lib/node_modules/tl/node_modules/tilelive-cache/index.js:265:12)
    at /usr/lib/node_modules/tl/node_modules/locking-cache/index.js:84:17
    at /usr/lib/node_modules/tl/node_modules/async/lib/async.js:760:23
    at /usr/lib/node_modules/tl/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/tl/node_modules/async/lib/async.js:718:13
```

Please let me know, what I'm doing wrong?  Thanks!

**Comment by sethfitz** [comment]
That should be right, though I'm not sure what the `-r` flag to `npm install` does. Can you check to see if `node_modules/@mapbox/mbtiles` exists? If not, try without the `-r`.

**Comment by secretgh** [comment]
+1 Is the mbtiles://./file.mbtiles sink a windows command? I am running on mac.

**Comment by sethfitz** [comment]
Nope, that's from MacOS / Linux.

**Comment by PositivPy** [comment]
I have the same issue. I tried to install an older version of nodejs (9.11.1) but it's still not working. `node_modules/@mapbox/mbtiles` exists.

It's concerning that a package `mbtiles` is not be able to process `mbtiles`.

**Comment by sethfitz** [comment]
I think what's going on here is that `tl` (and `tilelive-http`) is installed globally (`npm install -g tl`) and it's looking for a globally-installed version of `@mapbox/mbtiles`, which doesn't exist. A local one does, but `tl` isn't able to look for it.

2 approaches that should work:

1. install `@mapbox/mbtiles` globally: `npm install -g @mapbox/mbtiles` (in addition to `tl` and any other tilelive modules you might need)
2. install everything locally (no `-g` argument) and invoke `tl` using `node_modules/.bin/tl` to use the locally-installed version.
