### ISSUE TITLE
Syntax error in tl dependencies (Namely tilelive)

### ISSUE THREAD

**Issue by mohsentaleb** [mojodna/tl#7]
I just upgraded my node to v0.12.5 and also tl module to the latest version.
When running `tl copy` command I get this error: 

```
\AppData\Roaming\npm\node_modules\tl\node_modules\tilelive-streaming\node_modules\tilelive\lib\statistics.js:24
    set remaining() {}, // read-only
                  ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Mohsen\AppData\Roaming\npm\node_modules\tl\node_modules\tilelive-streaming\node_modules\tilelive\lib\scheme.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by sethfitz** [comment]
This was fixed upstream in `tilelive-streaming` and applied here in b2b59ee6a2684b8e88db14dad115e388a9013c31

I just pushed out a v0.4.0 release that solves this.

See also #5
