### ISSUE TITLE
Application Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by mohsentaleb** [mojodna/tl#8]
`tl copy` exits with the following error message:

```
Error: The specified procedure could not be found.
C:\Users\Mohsen\AppData\Roaming\npm\node_modules\tilelive-vector\node_modules\mapnik\lib\binding\node-v14-win32-x64\mapnik.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Mohsen\AppData\Roaming\npm\node_modules\tilelive-vector\node_modules\mapnik\lib\mapnik.js:26:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
C:\Users\Mohsen\AppData\Roaming\npm\node_modules\tl\lib\commands\copy.js:71
          throw err;
                ^
Error: Invalid tilesource protocol: tmsource:
```

my `npm list --depth=0 -g` output:

```
\AppData\Roaming\npm
├── browserify@10.1.3
├── grunt-cli@0.1.13
├── mapnik@3.3.0
├── tilelive@5.8.1
├── tilelive-file@0.0.3
├── tilelive-tmsource@0.3.0
├── tilelive-tmstyle@0.4.0
├── tilelive-vector@3.2.7
└── tl@0.4.0
```

**Comment by springmeyer** [comment]
Hi @mohsentaleb - This problem is due to a broken node-mapnik installation. Have you tried re-installing fresh? See https://github.com/mapnik/node-mapnik/wiki/Troubleshooting#the-specified-procedure-could-not-be-found for details on this specific error. After reading and following that can you share with us the error you see from using `ctypes.CDLL`...?

**Comment by wilhelmberg** [comment]
@mohsentaleb the broken mapnik install might be due to the fact that, at the moment, we are stuck at compiling mapnik with VS2014 CTP4.
Hope that these problems will be gone in a few weeks, as VS2015 is about to be released soon and we plan to move to it as soon as possible.

If you have installed a newer (than VS2014 CTP4) vcredist or Visual Studio itself, it will render the installed CTP4, and thus mapnik, unusable.

Two possible solutions come to my mind:

1.

Unistall everything newer than `2014 CTP4`: vcredists and VS.
Reinstall CTP4 redist as outlined here:
https://github.com/mapnik/node-mapnik/#windows-specific

2.
- use our custom node.exe https://mapbox.s3.amazonaws.com/node-cpp11/v0.10.33/x64/node.exe
- download https://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x64-mini.7z
- extract `vcredist_x64-mini.7z`
  - next to where you put our `node.exe` **and**
  - into the `lib\binding\node-v11-win32-x64` directory for your mapnik install

The final release of VS2015 is scheduled by Microsoft in about two weeks.
After that we we will need about two weeks to move all our build systems to 2015.
I hope, that then these problems won't occur anymore.

**Comment by mohsentaleb** [comment]
@BergWerkGIS Thanks! will give it try after this.
BTW do you also have hints for running this on a CentOS x64 machine?

I get this error: 

```
node: symbol lookup error: /node-v0.12.6-linux-x64/lib/node_modules/tilelive-vector/node_modules/mapnik/lib/binding/node-v14-linux-x64/mapnik.node: undefined symbol: _ZNK6mapnik9image_any7getSizeEv
```

my npm list:

```
mapnik@3.4.0
npm@2.11.2
tilelive@5.8.2
tilelive-file@0.0.3
tilelive-tmsource@0.3.0
tilelive-tmstyle@0.4.0
tilelive-vector@3.2.7
tl@0.4.0
```

**Comment by wilhelmberg** [comment]
@mohsentaleb sorry, I don't have any experience with CentOS,

**Comment by mohsentaleb** [comment]
@BergWerkGIS I mean, not specifically CentOS, but Linux version of mapnik in general.
